### ISSUE TITLE
[1.16.1] Exception in server tick loop

### ISSUE THREAD

**Issue by realTIMematrix** [Exopandora/WorldHandler#13]
Hi,

the game crash with the latest 1.16.1 forge version

Minecraft: 1.16.1
Forge: 32.0.69
WorldHandler-1.16.1-2.10.2.jar

Steps to reproduce:

1. Start game
2. Create new single player game
3. Crash when the game reaches 100% loaded and try to join the world

[Crash Report](https://pastebin.com/ykhHjiiN)

[Latest Log](https://pastebin.com/ZC9VvDWB)

**Comment by Exopandora** [comment]
This is likely due to a breaking change in forge 1.16.1-32.0.67. I will look into it tomorrow. Thanks for the report. For the moment i advise you to use forge 1.16.1-32.0.66 or lower
