### ISSUE TITLE
I Cant figure out how to use this mod on servers

### ISSUE THREAD

**Issue by 0redfn** [Exopandora/WorldHandler#19]
I just need a way to use this mod on a server. when i try to use it, it says change permission query

**Comment by Exopandora** [comment]
You just need to install it on your client. The message "You do not have permission to use the World Handler" pops up if the mods detects that you do not have enough permissions (i.e. you are not an operator) on this server to use command. You can disable that check in the config file. It is located in .minecraft/config/worldhandler/worldhandler.toml. In that file you would need to change `permission_query = true` to `permission_query = false`. Alternatively you can install [configured](https://www.curseforge.com/minecraft/mc-mods/configured) to change the settings ingame.

**Comment by 0redfn** [comment]
tysm, i will see if it works asap

**Comment by 0redfn** [comment]
is there a way to use this if i am not an admin?

**Comment by Exopandora** [comment]
As i said this disables the permission check and you can use the gui. You will be able to send the commands but they may not have any effect if you dont have the required permissions.
