### ISSUE TITLE
Fill button is not being enabled after setting block id and coordinates.

### ISSUE THREAD

**Issue by AlbertoSaenz** [Exopandora/WorldHandler#20]
Hi, I am doing something wrong?, I'm using the tools to select 2 points, then enter the block ID when using the fill GUI, but the fill button remains grayed out.

Minecraft 1.19, the latest forge and mod installed from curse forge.

Thank you.

**Comment by Exopandora** [comment]
What text do you enter? The button should automatically enable itself if you enter a vaild block resource location i.e. 'grass_block' or 'minecraft:stone'. Note that spaces will be automatically replaced with '_'.

**Comment by AlbertoSaenz** [comment]
Thank you for your response, I want to use it to delete blocks so I tried using:  minecraft:air, air alone, and 0.
It works with cave_air and void_air, but i really don't know if i can use it the same way or they are for different purposes.

**Comment by Exopandora** [comment]
Yes that must be an oversight by me in the 1.19 port. I will fix that later today. Thank you for the report.
