### ISSUE TITLE
[Suggestion] Add Change GUI Hotkey options in mod options

### ISSUE THREAD

**Issue by vlad-del576** [Exopandora/WorldHandler#21]
### The Issue
I have a mod-pack with Minecraft 1.12.2 and I installed World Handler in it. But I can't open the GUI because the "V" hotkey that opens the GUI is conflicting with another mod (Techguns) that uses the same hotkey that hasn't the option to change that specific hotkey.
So an option that allows you to change the hotkey that opens the GUI might help.

**Comment by Exopandora** [comment]
Just check the vanilla keybind options menu, its there

**Comment by vlad-del576** [comment]
I found it. Thanks!
