### ISSUE TITLE
Changing the slider parameters in the config doesn't change the maximum in game.

### ISSUE THREAD

**Issue by SMonroeC** [Exopandora/WorldHandler#22]
When I increase the max-item-attributes value from 100, the minimum end of the slider follows suit, but the maximum stays at 100.  Here's a video of the phenomena:
https://youtu.be/ZlHt1ngG5jc

I am running a world in 1.19 with Forge 41.0.98 and the latest Java version. I am also using the following mods: AttributeFix, Just Zoom, Konkrete, Neat, Spark, Oculus, Radon, Rubidium, and Radium Reforged.

Thanks

**Comment by Exopandora** [comment]
Thanks for the report, a new version should be available soon.
