### ISSUE TITLE
suggest: add locate and tp command

### ISSUE THREAD

**Issue by shownfish** [Exopandora/WorldHandler#24]
Can you add locate and tp command to it？It will be very convenient to find structures when using the mod that add lots of structures

**Comment by Exopandora** [comment]
Do you mean the tp command that you get as a response from the locate command or the teleport command itself to i.e. teleport to other players?

**Comment by Exopandora** [comment]
Personally i dont't see much benefit in adding a gui for /tp as it is always faster to just type the command with autocomplete.

**Comment by shownfish** [comment]
I see，the locate gui will be great，nice work

**Comment by Exopandora** [comment]
A new version will be available shortly, thank you for the suggestion.
