### ISSUE TITLE
World Handler 1.20-3.4.3 crash with MC Forge 47.0.35 (1.20.1)

### ISSUE THREAD

**Issue by sacu85** [Exopandora/WorldHandler#25]
I have a crash when trying to run MC Forge 47.0.35 (1.20.1) along with World Handler 1.20-3.4.3. Please see the attached logs.

[crash-2023-07-03_16.36.31-fml.txt](https://github.com/Exopandora/WorldHandler/files/11938011/crash-2023-07-03_16.36.31-fml.txt)
[latest.log](https://github.com/Exopandora/WorldHandler/files/11938012/latest.log)

**Comment by Exopandora** [comment]
Thanks for the report. A new version with a fix has been released. Let me know if you encounter any other issues.

**Comment by sacu85** [comment]
Everything is fine now. Thank you very much.
