### ISSUE TITLE
Suggestion: Default GUI Tabs

### ISSUE THREAD

**Issue by StarNightKitty** [Exopandora/WorldHandler#26]
Hello, I would like to suggest a change with the default tabs, it would be nice to include those default tabs under the "usercontent" folder as modifiable js/json files, so those that would like to edit/remove those tabs can do it by simply deleting/modifying the js/json files.

**Comment by Exopandora** [comment]
Thanks for the suggestion. Categories (tabs) can now be configured in `.minecraft\config\worldhandler\usercontent\categories.json`.
