### ISSUE TITLE
Crash in dedicated server

### ISSUE THREAD

**Issue by vico93** [Exopandora/WorldHandler#4]
Hi!

I know WH is for clients, but i sync my dedicated server folder with my client profile using git, so i need to keep the jar in dedicated server too.

So is possible to make this mod "do nothing" when installed on a dedicated server?

Crash report of the last time i tried to run the server with wh installed: https://paste.dimdev.org/diheyuweku.mccrash

**Comment by Exopandora** [comment]
I will look into it tomorrow. A potential workaround is to add the jar file to your .gitignore

**Comment by vico93** [comment]
Thanks!
