### ISSUE TITLE
Several Suggestions

### ISSUE THREAD

**Issue by sepsol** [Exopandora/WorldHandler#5]
a) It would be great if you could work on the buttons layout by seperating time/ weather/ gammode/ difficulty related buttons.

b) It would be great if this was available vertically on the left side of the 'inventory GUI', or integrate it with the playerlist (TAB) button, that would be great for servers. I always confuse these menus as I frequently use them.

c) I wish these two commands were on the main page alongside time and weather related commands:
/gamerule doDaylightCycle true/false
/gamerule doWeatherCycle true/false

d) It would be awesome if this mod supported server-side functions. I wish I was able to see other players' stats in 'Player' section on main menu and teleport them or do other stuff with them, like giving them a potion effect.

**Comment by Exopandora** [comment]
a) They are already aligned for the best cohesion. If you want to you can create a prototype for an alternative layout
b) This could be similar to the "shortcut buttons" currently only available through the settings. They are a top row of the icon buttons
c) This could be realised with "programmable" buttons
d) Thats a pretty good idea. But i dont know if this can be implemented client side only (As this mod is intended to be used for)

**Comment by sepsol** [comment]
How can I add 'programmable' buttons?

**Comment by Exopandora** [comment]
Its not implemented

**Comment by sepsol** [comment]
I will try to come up with a layout and send it to you, the problem is that I'm not that familiar with Minecraft commands. This could take a while.

**Comment by Exopandora** [comment]
Currently the buttons are oriented as follows:

Shortcuts:
- Red: Daytime
- Lime: Difficulty
- Cyan: Settings
- Blue: Weather (Close to daytime for quick access)
- Brown: Butcher (Could be relocated to entites)
- Purple: Potions (As potions do not fit any category but entities maybe)
- Orange: Gamemodes

Rows:
- Pink: Everything found in the game world
- Green: General game concepts/abstractions
- Black: Misc

Reference:

![Image](https://i.imgur.com/hRdYyFx.png)

Generally the GUI is built to have two columns. The left one is for general navigation/subcategory selection and the right one is for the actual settings/configuration.

**Comment by Exopandora** [comment]
Closed due to inactivity
