### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by JabberJibber** [Exopandora/WorldHandler#8]
Tried the Replace Blocks command through the GUI.  Works wonderfully, it just leaves an outline of the area that I replaced blocks, which is distracting

**Comment by Exopandora** [comment]
This is intentional as the current block selection will be highlighted. If you find the outline distracting you can disable it in config file. The options is called `highlight_blocks`

**Comment by JabberJibber** [comment]
Oh, how do I do that? Sorry, new to modding

**Comment by Exopandora** [comment]
For the latest version you can navigate to `..\.minecraft\config\worldhandler\worldhandler.toml` and edit it with a normal text editor. In there you find a line with `highlight_blocks = true`. Change that line to `highlight_blocks = false` and save the file. There is a chance that the game will instantly update the setting but if not restart the game and the outline will be gone.
